---
output: 
    github_document:
        html_preview: false
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# BGCkit

<!-- badges: start -->
<!-- badges: end -->

## Installation

You can install the development version of BGCkit like so:

``` r
# install.packages("devtools")
devtools::install_github("Asa12138/BGCkit")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(BGCkit)
## basic example code
```

## MiBIG database


```{r eval=FALSE}
# get_mibig_db(file = "../temp/mibig_json_4.0.tar.gz")
load_mibig_db() -> mibig_db
mibig_db2df(mibig_db) -> mibig_df
```

## Antismash


```{r eval=FALSE}
how_to_do_bgc("antismash")
```

```{r}
read_antismash_json("../temp/AAB-S02R5_42_v7.1.0/AAB-S02R5_42.json") -> AAB_S02R5_42
AAB_S02R5_42

get_BGCs_from_BGC_json(AAB_S02R5_42)
plot_BGC(AAB_S02R5_42, region_id = "AAB-S02R5_k55_4109967_flag0_multi6.7266_len8952.region001")
```



## Big-scape

```{r eval=FALSE}
how_to_do_bgc("big-scape")
```

```{r}
read_big_scape_dir("../temp/network_files/2024-05-27_14-21-19_hybrids_glocal/") -> big_scape_res
big_scape_res

plot_BGC_class(big_scape_res)

trans_net(big_scape_res, class = "RiPPs") -> NRPS_net

plot(NRPS_net,
  group_legend_title = "Product Prediction", main = "RiPPs GCF network",
  size_legend = T, size_legend_title = "Degree"
)
```


## Big-slice

```{r}
# read_big_slice_dir("~/Documents/R/Greenland2/data/big_slice_out/")->big_slice_res2
read_big_slice_dir("../temp/big_slice_test_out/") -> big_slice_res

big_slice_res

# open_big_slice_website(big_slice_res,port=123)

get_big_slice_db(big_slice_res, "bgc")

get_report_df(big_slice_res, "Greenland_MAGs")
```

## BGC_atlas

```
cd /data/home/jianglab/share/pc_DB/BGC_atlas

```

